### ISSUE TITLE
How to add more node types to this module?

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/node_revision_history#1]
The node_revision_history module only includes the revisions for default nodes types: pages and posts. How can it be configured to include all node types?

**Comment by markabur** [comment]
There is a bug in the module that makes it only work for content types whose machine name matches the human-readable name. Here is a PR that makes it work for other content types too: https://github.com/backdrop-contrib/node_revision_history/pull/2

**Comment by olafgrabienski** [comment]
@izmeez Are you interested to test the PR?

Btw, I guess, the maintainer isn't not active anymore. However, once the PR is RTBC for a while, the @backdrop-contrib/bug-squad can chime in.

**Comment by izmeez** [comment]
@markabur Thank you. Patch in https://github.com/backdrop-contrib/node_revision_history/pull/2 does work to show revisions in content types other than default nodes types: pages and posts. Unfortunately, there are other issues with this module to make it useful. I will need to identify them with specific issues. Nonetheless the patch works and appears simple enough that I will make it as RTBC.

**Comment by izmeez** [comment]
Unfortunately, I am not able to add labels to contrib modules, so I am unable to mark it as reviewed and tested.

**Comment by argiepiano** [comment]
Since the maintainer is no longer around, and since this is a bug, there is no need to wait. I'm merging it on behalf of the @backdrop-contrib/bug-squad

**Comment by argiepiano** [comment]
Well, even though I'm part of the @backdrop-contrib/bug-squad, I don't have permission to merge PRs in this repo. It happens with older repos. Someone else in the @backdrop-contrib/bug-squad available?

**Comment by herbdool** [comment]
I've given the bug squad permissions to this module and I'll merge this fix.

**Comment by herbdool** [comment]
I've merged it and made a release.
